config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  resources :posts
  resources :admin_users

    root to: "users#index"
  end

  resources :posts
  devise_for :users, skip: [:registration]
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User

end

app/models/post.rb
class Post < ActiveRecord::Base
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  validates_presence_of :date, :rationale
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :first_name, :last_name
  has_many :posts

  def full_name
    last_name + ", " + first_name
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_filter :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access this page."
        redirect_to root_path
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to @post, notice: 'Your post was created successfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to @post, notice: 'Your post was edited successfully.'
  end

  def show
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: 'Your post was deleted successfully'
  end

  private

  def post_params
    params.require(:post).permit(:date, :rationale, :status)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Overtime
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .row
        .col-md-12
          = render 'shared/nav'
          = yield
    = js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false)

app/views/posts/_form.haml
= form_for @post, class: "form-horizontal" do |f|
  - if @post.errors.any?
    - @post.errors.full_messages.each do |error|
      = js add_gritter(error, title: "Overtime App Notification", sticky: false)

  .form-group
    = f.label :date, class: "col-sm-2 control-label"
    = f.date_field :date, class: "form-control"
  .form-group
    = f.label :rationale, class: "col-sm-2 control-label"
    = f.text_area  :rationale, class: "form-control"
  = render partial: 'status', locals: { f: f } if current_user.type == 'AdminUser'
  .form-group
    = f.submit "Save", class: "btn btn-primary btn-block"

app/views/posts/_post.haml
%tr
  %td
    = post.id
  %td
    = post.date
  %td
    = post.user.full_name
  %td
    = truncate(post.rationale)
  %td
    = link_to 'Edit', edit_post_path(post), id: "edit_#{post.id}"
  %td
    = link_to 'Delete', post_path(post), id: "delete_#{post.id}_from_index", method: :delete

app/views/posts/_status.haml
.form-group
  = f.radio_button :status, 'submitted'
  = f.label :status, 'Submitted'

  = f.radio_button :status, 'approved'
  = f.label :status, 'Approved'

  = f.radio_button :status, 'rejected'
  = f.label :status, 'Rejected'

app/views/posts/edit.haml
%h1 Edit
= render 'form'

app/views/posts/index.haml
%h1 Posts
%table.table.table-striped.table-hover
  %thead
    %tr
      %th #
      %th Date
      %th User
      %th Rationale
      %th
      %th 
  %tbody
    = render @posts

app/views/posts/new.haml
= form_for @post do |f|
  = f.date_field :date
  = f.text_area  :rationale
  = f.submit "Save"

app/views/posts/show.haml
= @post.inspect

app/views/shared/_nav.haml
.logo
  %h1 Overtime App
-# TODO:
- if current_user
  %ul.custom-nav.nav.nav-tabs
    %li{:class => "#{active?(root_path)}"}
      = link_to 'Home', root_path
    %li{:class => "#{active?(posts_path)}"}
      = link_to 'Time Entries', posts_path
    %li{:class => "#{active?(new_post_path)}"}
      = link_to 'New Entry', new_post_path, id: 'new_post_from_nav'
    %li.dropdown.pull-right
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        Options
        %strong.caret
        %ul.dropdown-menu
          -# TODO:
          - if current_user.try(:type) == 'AdminUser'
            %li
              = link_to 'Admin Dashboard', admin_root_path
            %li.divider
          %li
            = link_to 'Log Out', destroy_user_session_path, method: :delete